pipeline:
  name: test
  identifier: test
  projectIdentifier: Chetan_new_git_x
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: srv
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: a1
                  variables:
                    - name: ab
                      type: String
                      value: hvb
          environment:
            environmentRef: env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra
            serviceOverrideInputs:
              variables:
                - name: va1
                  type: String
                  value: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: s2
                  identifier: s2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo <+serviceVariables.ab>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: var1
      type: String
      description: ""
      value: hello
    - name: var2
      type: String
      description: ""
      value: bye
